# Generated by Django 5.2.7 on 2025-10-13 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('account_password', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_code', models.CharField(max_length=20)),
                ('account_type', models.CharField(max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='users.users')),
            ],
            options={
                'verbose_name': '계좌',
                'verbose_name_plural': '계좌 목록',
            },
        ),
    ]
