# Generated by Django 5.2.7 on 2025-10-20 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Histories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=20)),
                ("desc", models.TextField()),
                ("inout_type", models.CharField(max_length=20)),
                ("transact_type", models.CharField(max_length=20)),
                ("transacted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories_records",
                        to="accounts.accounts",
                    ),
                ),
            ],
            options={
                "verbose_name": "거래",
                "verbose_name_plural": "거래 내역",
            },
        ),
    ]
